@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml
HIDE_STEREOTYPES()

MsgChannel(node_1, "startChannel")
MsgChannel(node_2, "nullChannel")
PubSubChannel(node_3, "errorChannel")
MsgChannel(node_4, "channel#0")
MsgChannel(node_5, "channel#1")
ChannelAdapterLeft(node_6, "errorLogger")
MessageTranslator(node_7, "ConsumerEndpointFactoryBean#0")
Filter(node_8, "ConsumerEndpointFactoryBean#1")
MessageTranslator(node_9, "ConsumerEndpointFactoryBean#2")

Send(node_3, node_6)
Send(node_1, node_7)
Send(node_7, node_4)
Send(node_4, node_8)
Send(node_8, node_5)
Send(node_8, node_3)
Send(node_5, node_9)
Send(node_9, node_2)
@enduml
