@startuml
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/EIP-PlantUML/main/dist/EIP-PlantUML.puml

MsgChannel(node_1, "startChannel")
MsgChannel(node_2, "nullChannel")
PubSubChannel(node_3, "errorChannel")
ChannelAdapterLeft(node_6, "errorLogger")
MessageTranslator(node_7, "testFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#0")
Filter(node_8, "testFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#1")
MessageTranslator(node_9, "testFlow.org.springframework.integration.config.ConsumerEndpointFactoryBean#2")

Send(node_3, node_6)
Send(node_1, node_7)
Send(node_8, node_3)
Send(node_9, node_2)
Send(node_7, node_8)
Send(node_8, node_9)
@enduml
